- hosts: localhost

#프롬프트 앤서블 실행할때 패스워드 입력
  vars_prompt:
    - name: db_password
      prompt: "MariaDB 비밀번호를 입력하세요"
      private: yes  # 입력 내용을 숨김


  tasks:
    - name: AMI Images
      amazon.aws.ec2_ami_info: # 변경된 모듈명
        filters:
          "name": "Amazon Linux 2023 AMI"
          "state": "available"
        region: ap-northeast-2
        owners: "amazon"
      register: ami_info

    - name: Create VPC
      amazon.aws.ec2_vpc_net: # 변경된 모듈명
        name: MyVPC
        cidr_block: 10.0.0.0/16
        region: ap-northeast-2
        tags:
          - key: Name
            value: MyVPC
          - key: Environment
            value: Production
      register: vpc

    - name: Create Public Subnet
      amazon.aws.ec2_vpc_subnet: # 변경된 모듈명
        state: present
        vpc_id: "{{ vpc.vpc.id }}"
        cidr: 10.0.1.0/24
        map_public: yes
        region: ap-northeast-2
        tags:
          - key: Name
            value: MyPublicSubnet
      register: subnet

    - name: Create DB Subnet
      amazon.aws.ec2_vpc_subnet: # 변경된 모듈명
        state: present
        vpc_id: "{{ vpc.vpc.id }}"
        cidr: 10.0.10.0/24
        map_public: no
        region: ap-northeast-2
        tags:
          - key: Name
            value: MyDBSubnet
      register: dbsubnet

    - name: Create Internet Gateway
      amazon.aws.ec2_vpc_igw: # 변경된 모듈명
        vpc_id: "{{ vpc.vpc.id }}"
        region: ap-northeast-2
        tags:
          - key: Name
            value: MyIGW
      register: igw

    - name: Create Route Table
      amazon.aws.ec2_vpc_route_table: # 변경된 모듈명
        vpc_id: "{{ vpc.vpc.id }}"
        region: ap-northeast-2
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ igw.gateway_id }}"
        tags:
          - key: Name
            value: MyRT
      register: route_table

    - name: Associate Route Table
      amazon.aws.ec2_vpc_route_table: # 변경된 모듈명
        route_table_id: "{{ route_table.route_table.id }}"
        vpc_id: "{{ vpc.vpc.id }}"
        subnet_id: "{{ subnet.subnet.id }}"
        region: ap-northeast-2

    - name: Create Security Group
      amazon.aws.ec2_group: # 변경된 모듈명
        name: my_security_group
        description: Security group for my VPC
        vpc_id: "{{ vpc.vpc.id }}"
        region: ap-northeast-2
        tags:
          - key: Name
            value: MySG
      register: security_group

    - name: DB 서브넷 그룹 생성
      amazon.aws.rds_subnet_group:
        state: present
        name: my_subnet_group
        description: My DB subnet group
        subnets: "{{dbsubnet.subnet.id}}"

    - name: DB 보안 그룹 생성
      amazon.aws.ec2_group:
        name: my_db_security_group
        description: Security group for RDS instance
        vpc_id: "{{vpc.vpc.id}}"
        rules:
          - proto: tcp
            from_port: 3306
            to_port: 3306
            cidr_ip: 0.0.0.0/0
        tags:
          Name: my_db_security_group
        register: DBSG

    - name: RDS 인스턴스 생성 (마리아DB)
      amazon.aws.rds_instance:
        engine: mariadb
        db_instance_identifier: mydbinstance
        allocated_storage: 20
        db_instance_class: db.t2.micro
        master_username: root
        master_user_password: "{{ db_password }}"
        db_subnet_group_name: "{{dbsubnet.subnet.id}}"
        vpc_security_group_ids:
          - "{{ DBSG.group_id }}"
        wait: yes
        tags:
          Name: mydbinstance
      register: rds_instance

    - name: Create EC2 Instance
      amazon.aws.ec2_instance: # 변경된 모듈명
        key_name: elb-public
        instance_type: t2.micro
        image: "{{ ami_info.images[0].image_id }}"
        wait: yes
        group_id: "{{ security_group.group_id }}"
        vpc_subnet_id: "{{ subnet.subnet.id }}"
        region: ap-northeast-2
        tags:
          - key: Name
            value: MyEc2
        user_data: |
          #!/bin/bash
          echo "{{ rds_instance.instance.endpoint }}" > ~/testfile
